### ISSUE TITLE
Consider defining CSS vars in `:root`

### ISSUE THREAD

**Issue by michaellenaghan** [imperavi/superkube#13]
**NOTE**: This issue introduced two different topics. I've now created a new issue, #17, to focus on one of them, and re-titled this one to focus on the other.

===

I'll start by saying: I'm not a CSS expert. :-) In fact, I'm only an occasional web developer. Still...

Compared to other CSS frameworks I've seen, Superkube seems to be using CSS vars in an unusual way. I think I'd summarize it like this: Superkube seems to use CSS vars as a replacement for SASS vars. 

I think other frameworks do things differently.

In other frameworks I think CSS vars are an *alternative* to SASS vars, not a replacement. The point, mostly, is that they allow users to customize frameworks without using SASS at all. For example, from Bootstrap's documentation:

> Bootstrap includes many [CSS custom properties (variables)](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) in its compiled CSS for real-time customization without the need to recompile Sass.

Superkube, by contrast, is documenting things like this:

> For the nav module, you can override default colors. You can do this in your custom SCSS. See also how to [customize](https://imperavi.com/superkube/docs/getting-started/customize/) the framework.
>
>     .nav {
>         --nav-link-color: var(--palette-active-base);
>         --nav-link-hover-color: var(--palette-black);
>         --nav-link-active-color: var(--palette-black-40);
>     }

That seems odd. With that kind of usage, there's no advantage over SASS vars. In fact, it seems like the old-school approach where you override a framework's CSS classes in your own CSS — a problem SASS vars were designed to overcome.

Bootstrap does something that, I think, makes more sense: it defines CSS vars *in terms of* SASS vars:

```
    --#{$prefix}navbar-color: #{$navbar-light-color};
```

If I change the value of `$navbar-light-color` it becomes the new default rather than an override. That means that less CSS is generated, and that the generated CSS is clearer.

One other difference, I think, is with where and how CSS vars get declared.

In the original CSS var-based frameworks I saw, all vars were defined in `:root`. They *could* be scoped to different contexts by users — e.g., use this value from here and down, that value from there and down — but at the *framework* level there wasn't much point. How many frameworks every override their own vars?

More recently, some frameworks — I think Bootstrap is one — seem to be scoping their CSS vars as a way of attaching them to "components".

I have to say, I'm not clear on the value. At least, not for most users. Even with all vars defined in `:root` you can still have modules like `navbar`, and `navbar` can still have its own `:root` declaration, and all of the navbar module's CSS vars can still use a `--navbar` prefix... It's still a component, even though its vars are in a global namespace.

So: I'd suggest that Superkube place all CSS vars in `:root`. It simplifies things for the users CSS vars are really targeted at: those who aren't using SASS. And it doesn't make like any more difficult for SASS users either. In fact, I'd say that it makes things easier. With Superkube's current approach I have to keep going back to the docs to figure out the right scope for my overrides.

(If there's a benefit to scoping the vars it just hasn't occurred to me yet!)

**Comment by jamieg270** [comment]
There is utility and logic in scoping a css var to a specific class or element. 

Heres a quick story to demonstrate: I worked on a site where a previous developer used css vars specifically set for one component but then reused them elsewhere on a different component. They could do this because it was declared on :root.  I'm not sure why they did this, maybe they were ignorant of the consequences or simply did it as a lazy quick fix..

This generated unexpected results when we changed that css var for the original component and we suddenly had an unrelated component change colour that we couldn't have anticipated.

A css var scoped to a specific component cannot be reused by accident or design on a component/element outside its scope.

By scoping a css var to a specific component you prevent its deliberate or accidental use elsewhere in the site/application which could cause problems down the line. 

Scoping in this way enforces good practice and prevents accidental errors with css var usage.

The other reason you would scope css vars is it can be easier and cleaner to create variants of the component simply by redeclaring local scope css variables with a new value in a modifier class rather than having to override the original components css. This makes for cleaner more logical and more succinct css.

As a rule of thumb if the css var doesn't _need_ to be in the global scope then it _probably shouldn't_ be in the global scope.

Coming back to the original question I think the intent for SuperKube (this is totally my own conjecture cant speak for the author!) is they've set up the basics for you in the nav component with a few ready build modifier classes. You  then create your own nav variants by creating a modifier class that restates the css vars rather than manipulating a scss variable. Their .nav-light , .nav-primary, .nav-muted modifier classes for the nav component  are modifier classes that restates the following variables to get the desired result :

    --nav-link-color
    --nav-link-hover-color
    --nav-link-active-color

I don't think Superkube is using css vars as a replacement for scss vars they both have different purposes albeit with some overlap and both have different strengths and weaknesses. They are really complimentary. SuperKube are using a 'utility-first framework' design approach that really leans into css variables and a lot of the scss variables are then declared as css variables for this purpose.

In situations where there is no massive advantage to declaring it as a scss variable first going straight to a css variable is a perfectly reasonable judgement call.

In this case the intended use of modifier classes means you do not have to override the css of a component you can just restate the css vars to effect the change you want with a user created modifier class. 

The author has probably decided this approach on this basic component trumps any advantage the declaring of a scss variable brings, it gives you a very marginal benefit of being able to change the base .nav component without a modifier class. but thats not worthwhile when the expected use of modifier classes can effectively do the same thing without a great deal of overhead.

Saying that however there is nothing preventing you from adding your own scss variable to the framework specifically to cover the base .nav css variable so you can manipulate the base declared css vars for the .nav component before preprocessing. All you'd need to do is disable the core module and add your own modified version of it as a custom module with your changes within it. SuperKube is very extendable and very easy to modify.

I hope that is helpful.

**Comment by michaellenaghan** [comment]
Thanks for taking the time to write that. I spent some time thinking about this.

> Heres a quick story to demonstrate: I worked on a site where a previous developer used css vars specifically set for one component but then reused them elsewhere on a different component. They could do this because it was declared on :root. I'm not sure why they did this, maybe they were ignorant of the consequences or simply did it as a lazy quick fix.

Misuse is misuse, no? 

Let's say that the original component was:

```css
.panel {
    --panel-color: blue;
    background-color: var(--panel-color);
}
```

Let's say that that very same developer needed a red panel somewhere; he would have added this to his stylesheet:

```css
.panel {
    --panel-color: red;
}
```

making all panels red everywhere. Even if, unknown to (or forgotten by :-) him, blue panels were in fact wanted elsewhere.

In other words, with CSS vars, unique uses always require unique scopes. If you didn't realize that your use was *not* unique, you'd create a problem no matter what.

(That's not a CSS vars problem, that's a CSS problem. Maybe the developer didn't know about the existing component at all, and just happened to use the same class name?)

I understand the *intent* of the scoping. I understand the value of modularity. I guess I'm arguing that scoping CSS vars increase the cost, the friction, of using the framework, without actually providing much benefit. CSS class names provide a *kind* of scope, but it's not *modular* scope.

(With the current approach, I'm constantly having to look at the source to see what the scope of a given Superkube var actually is; the docs almost never say.)

My thesis — possibly mistaken — is that the primary benefit of CSS vars is to allow customization of the framework without using SASS. (If you're using SASS, why not use SASS vars?)

If that's true, then with this suggestion users would just need to know the name of the var to change its value; the scope would always be `:root`.

And it wouldn't stop them from creating unique scopes when they needed unique values:

```css
.panel-blue {
  --panel-color: blue;
}
.panel-red {
  --panel-color: red;
}
```

That's exactly what they'd need to do anyway even *with* scoped CSS vars.

P.S. My original issue described two different things. You've focused on one of them; I'm going to split the other, initializing CSS vars using SASS vars, out to its own issue.

**Comment by michaellenaghan** [comment]
I don't think there's any interest in this, so I'll close it.

For what it's worth, the issue I reported in #19 is a good example of what I meant about the CSS scopes not being modular. They don't encapsulate. Likewise, I think, #20.
